### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Aomex** [xinghaix/download-manager#11]
1，任务列表卡片式的布局还是不够紧凑，上下留白太多，如果可以自定义列表的样式，就更好了。

2，图标略小

3，文件类型分类功能

4，任务列表上方的清空列表仅仅是清空，应该有个选项，可供选择，是否清空时同时删除文件。

**Comment by Aomex** [comment]
5，任务列表里，删除与清除按钮挨的太近容易误点，建议删除时给个提示是否删除。

**Comment by xinghaix** [comment]
@Aomex 如果你有比较好的设计，可以发个图片或者链接。当前阶段样式不会由太大的改变，后期有计划重新设计样式
