### ISSUE TITLE
[建议] 希望能够添加右键菜单

### ISSUE THREAD

**Issue by L1cardo** [xinghaix/download-manager#13]
类似这种
![image](https://user-images.githubusercontent.com/33802186/80674688-30420b80-8ae5-11ea-898e-0c10a6a2fca0.png)

**Comment by xinghaix** [comment]
@L1cardo 这些操作可以直接点击相应位置实现，在设置中有详细说明

**Comment by L1cardo** [comment]
设置里面确实有，但是操作逻辑不符合常规，我没必要为每一个功能去记到底是右键还是左键。
个人认为右键进入二级菜单是比较好的逻辑

**Comment by xinghaix** [comment]
@L1cardo 嗯，我考虑下

**Comment by L1cardo** [comment]
关于这个  有什么想法吗

**Comment by xinghaix** [comment]
> 关于这个 有什么想法吗

会加上的
