### ISSUE TITLE
[建议]删除文件增加确认提示

### ISSUE THREAD

**Issue by ruinb0w** [xinghaix/download-manager#15]
我点了下垃圾桶文件就没了, 希望可以在设置中添加默认是清理还是删除如果不设置默认则提示确认删除

**Comment by xinghaix** [comment]
@ruinb0w 我研究下怎么把文件移动到回收站

**Comment by xinghaix** [comment]
@ruinb0w 把文件删除到回收站需要文件系统权限，只有ChromeOS才会给Chrome插件提供权限，其他系统比如Windows、Mac、Linux都没有这种权限。
如果要实现这种功能，只能另外写个客户端放在机子上，但会大大增加插件整体复杂度
