### ISSUE TITLE
[Suggestion] Clear List

### ISSUE THREAD

**Issue by NVHT** [xinghaix/download-manager#17]
Clear download list in Chrome Downloads should also clear the download list in the extension.

![image](https://user-images.githubusercontent.com/8341213/81479608-82d9a100-9224-11ea-9978-e6795bd7e80a.png)
** This is not related, but it is just minor annoyance.
"Download thislink" ---> "Download this link" with the space.

**Comment by xinghaix** [comment]
@NVHT Menu translation has been modified！

**Comment by xinghaix** [comment]
@NVHT Did your first question refer to this situation！
![1](https://user-images.githubusercontent.com/26537432/81517667-37330e80-936e-11ea-8671-e689670c6074.png)

**Comment by xinghaix** [comment]
https://github.com/xinghaix/download-manager/commit/e767475089dfc0d671e46080b1d7d6cfb9c6b9f1

**Comment by xinghaix** [comment]
https://github.com/xinghaix/download-manager/commit/e767475089dfc0d671e46080b1d7d6cfb9c6b9f1
