### ISSUE TITLE
[建议]希望下载进度能直接显示到图标上,另外能选择是否支持快捷键

### ISSUE THREAD

**Issue by JiaoYeTan** [xinghaix/download-manager#19]
快捷键貌似是默认Ctrl+Z的, 貌似没有办法取消快捷键, 希望大大能增加一个取消快捷键的按钮,

另外 希望大大能在图标上直接显示下载百分比
(单文件下载可以用进度条,多文件下载就用/隔开,或者取平均值)

**Comment by xinghaix** [comment]
@JiaoYeTan 修改和取消快捷快捷键可以在下图中操作

![批注 2020-06-07 201911](https://user-images.githubusercontent.com/26537432/83968509-53d64e00-a8fc-11ea-9f63-865973de4d24.png)

**Comment by xinghaix** [comment]
图标显示下载进度最近会完成

**Comment by JiaoYeTan** [comment]
> @JiaoYeTan 修改和取消快捷快捷键可以在下图中操作
> 
> ![批注 2020-06-07 201911](https://user-images.githubusercontent.com/26537432/83968509-53d64e00-a8fc-11ea-9f63-865973de4d24.png)

好像没办法取消快捷键,点X,他会自动改成Ctrl+Z,无法取消快捷键, 我是Edge浏览器,
![image](https://user-images.githubusercontent.com/36872913/83968704-a49a7680-a8fd-11ea-9403-3a76e36a039d.png)

**Comment by xinghaix** [comment]
> > @JiaoYeTan 修改和取消快捷快捷键可以在下图中操作
> > ![批注 2020-06-07 201911](https://user-images.githubusercontent.com/26537432/83968509-53d64e00-a8fc-11ea-9f63-865973de4d24.png)
> 
> 好像没办法取消快捷键,点X,他会自动改成Ctrl+Z,无法取消快捷键, 我是Edge浏览器,
> ![image](https://user-images.githubusercontent.com/36872913/83968704-a49a7680-a8fd-11ea-9403-3a76e36a039d.png)

先点一次 ×，然后会变成默认的，然后继续点击×

**Comment by JiaoYeTan** [comment]
> > > @JiaoYeTan 修改和取消快捷快捷键可以在下图中操作
> > > ![批注 2020-06-07 201911](https://user-images.githubusercontent.com/26537432/83968509-53d64e00-a8fc-11ea-9f63-865973de4d24.png)
> > 
> > 
> > 好像没办法取消快捷键,点X,他会自动改成Ctrl+Z,无法取消快捷键, 我是Edge浏览器,
> > ![image](https://user-images.githubusercontent.com/36872913/83968704-a49a7680-a8fd-11ea-9403-3a76e36a039d.png)
> 
> 先点一次 ×，然后会变成默认的，然后继续点击×

这是我这里的情况
![123](https://user-images.githubusercontent.com/36872913/83968919-f7286280-a8fe-11ea-960e-587389554ad0.gif)

**Comment by xinghaix** [comment]
@JiaoYeTan 尴尬，谷歌浏览器可以取消。你可以设置为不常用的组合键，从而避免误操作

**Comment by xinghaix** [comment]
@JiaoYeTan 我重新在edge浏览器上试了下，点击两次×之后，虽然显示有，但是不会再触发下载弹框了

**Comment by JiaoYeTan** [comment]
> @JiaoYeTan 我重新在edge浏览器上试了下，点击两次×之后，虽然显示有，但是不会再触发下载弹框了

好的,谢谢

**Comment by xinghaix** [comment]
@JiaoYeTan 图标上文件下载进度在1.0.6版本上已经实现。edge版本正在审核，google版本已经上线
