### ISSUE TITLE
请求上架Edge商店

### ISSUE THREAD

**Issue by ChirmyRam** [xinghaix/download-manager#2]
新版Edge扩展商店比Chrome商店访问更容易些，希望可以上架Edge商店。

**Comment by xinghaixuanwo** [comment]
感谢反馈！
已经提交到微软插件商店，正等待审核通过！
可能需要一些时间！等通过后我会再次给你发邮件。

________________________________
发件人: ChirmyRam <notifications@github.com>
发送时间: Saturday, March 14, 2020 3:28:15 PM
收件人: xinghaixuanwo/download-manager <download-manager@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [xinghaixuanwo/download-manager] 请求上架Edge商店 (#2)


新版Edge扩展商店比Chrome商店访问更容易些，希望可以上架Edge商店。

―

**Comment by ChirmyRam** [comment]
一个月过去了，可是在上架过程中遇到什么问题了吗？

**Comment by xinghaix** [comment]
@ChirmyRam 由于Edge要求插件中不能包含任何谷歌相关的内容，而为了更好的上线谷歌和微软插件商店，我得想个更好的方法来解决链接和名称冲突问题，所以得延后了，但一定会上架Edge的

**Comment by Aponio** [comment]
作者NB，这大概是我看到的界面设计比较不错的一个下载管理了。刚刚转战微软新EDGE，不过还是希望可以早点在微软商店看到这个插件（现在没上架微软商店其实问题也不大，毕竟新EDGE现在可以直接用谷歌商店下载的插件）。最后有个小小建议，希望点击“删除”的时候，可以弹出是否删除原文件。毕竟有时候我只是想删除下载记录，而不是把我源文件也删了。谢谢啦

**Comment by xinghaix** [comment]
最近开始重新尝试上架Microsofr Edge!

**Comment by xinghaix** [comment]
> 作者NB，这大概是我看到的界面设计比较不错的一个下载管理了。刚刚转战微软新EDGE，不过还是希望可以早点在微软商店看到这个插件（现在没上架微软商店其实问题也不大，毕竟新EDGE现在可以直接用谷歌商店下载的插件）。最后有个小小建议，希望点击“删除”的时候，可以弹出是否删除原文件。毕竟有时候我只是想删除下载记录，而不是把我源文件也删了。谢谢啦

删除下载记录可以点击 x 图标，删除图标是从磁盘删除文件，后面我再研究下如何删除文件到回收站

**Comment by ChirmyRam** [comment]
> 最近开始重新尝试上架Microsoft Edge!

敬候佳音。

**Comment by xinghaix** [comment]
@Aponio @ChirmyRam 插件已经上线Microsoft Edge插件商店

[![Microsoft Edge Version](https://img.shields.io/badge/dynamic/json?style=flat-square&label=Microsoft%20Edge%20Add-on&query=$.version&url=https://microsoftedge.microsoft.com/addons/getproductdetailsbycrxid/phalbpghhjknlmomkmimbamfceiddlic)](https://microsoftedge.microsoft.com/addons/detail/phalbpghhjknlmomkmimbamfceiddlic)

**Comment by ChirmyRam** [comment]
> @Aponio @ChirmyRam 插件已经上线Microsoft Edge插件商店
> 
> [![Microsoft Edge Version](https://camo.githubusercontent.com/16ae75e568927992b7800cd839bc94804afc7837/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f7374796c653d666c61742d737175617265266c6162656c3d4d6963726f736f6674253230456467652532304164642d6f6e2671756572793d242e76657273696f6e2675726c3d68747470733a2f2f6d6963726f736f6674656467652e6d6963726f736f66742e636f6d2f6164646f6e732f67657470726f6475637464657461696c73627963727869642f7068616c62706768686a6b6e6c6d6f6d6b6d696d62616d6663656964646c6963)](https://microsoftedge.microsoft.com/addons/detail/phalbpghhjknlmomkmimbamfceiddlic)

非常感谢！

**Comment by Aponio** [comment]
作者牛逼！已经用上了，非常感谢~
