### ISSUE TITLE
希望能增加一键清空无效任务的功能

### ISSUE THREAD

**Issue by qinyuz** [xinghaix/download-manager#21]
比如那些已经删除了的文件，但是列表里还是有这个任务

**Comment by xinghaix** [comment]
@qinyuz 之前有人提过这个。
目前下载的文件在磁盘中被删除后，点击下载弹框，文件区域会显示灰色。

很容易实现，但是由于目前弹框中顶栏（header）的按钮已经比较多了，我正在犹豫需不要加这个功能🤣

**Comment by qinyuz** [comment]
提个小建议，可以把“清空列表”按钮替换为“清空无效列表”

**Comment by xinghaix** [comment]
@qinyuz 已经改成下拉菜单的方式，已经提交到商店，等审核通过后你可以试下效果
