### ISSUE TITLE
（建议）关于清理任务

### ISSUE THREAD

**Issue by chploin** [xinghaix/download-manager#23]
你好，点击清理任务是否能变成一个下拉框，让用户根据需要自己选择：

删除磁盘文件
清除文件不存在的任务
清除已完成的任务
清除失败的任务
清除所有任务

**Comment by xinghaix** [comment]
@chploin 好想法，最近我会出一版

**Comment by xinghaix** [comment]
@chploin 新版本已上线chrome商店，edge商店审核较慢

**Comment by chploin** [comment]
辛苦辛苦~~

**Comment by chploin** [comment]
> @chploin 新版本已上线chrome商店，edge商店审核较慢

辛苦辛苦~~~
