### ISSUE TITLE
希望优化提示功能

### ISSUE THREAD

**Issue by MrZhao168** [xinghaix/download-manager#24]
插件自带的 通知 - 下载通知 && 完成通知 我这边测试没有听到提示音,只有一个小1,希望这里可以改成从下载链接那里飞一个图标飞到右上角下载插件那里,经常点了好几下下载才发现已经下载了三四个了文件了

**Comment by xinghaix** [comment]
@MrZhao168 通知以及通知提示音在最新版本（chrome商店）中问题基本全部解决
