### ISSUE TITLE
关于通知

### ISSUE THREAD

**Issue by dnknn** [xinghaix/download-manager#25]
Chrome.notifications谷歌通知接口, 不错的,原生+Windows桌面右下角🔔.
不仅是通知, 还能一键打开文件/文件夹.

https://developer.chrome.com/extensions/notifications
然后它能自定义超时时间以及是否自动关闭的. 
很多extension都能这样的自定义通知行为的,
download-manager可以增加吗?
假如人不在电脑,然后下载完成的提醒就可设置为不自动关闭.

🔔![bell](https://user-images.githubusercontent.com/10995302/85218902-5becbe00-b3d1-11ea-9374-0c866ba81437.gif)      ![0628235931](https://user-images.githubusercontent.com/10995302/85952409-abb42200-b99b-11ea-9870-e022ee166084.png) ![bell](https://user-images.githubusercontent.com/10995302/85218902-5becbe00-b3d1-11ea-9374-0c866ba81437.gif)🔔

![0629000531](https://user-images.githubusercontent.com/10995302/85952514-693f1500-b99c-11ea-988b-e5cdedd97255.png)

**Comment by xinghaix** [comment]
@dnknn 是指通知保留时间吧。可以

**Comment by dnknn** [comment]
@xinghaix ✉📧📨📩查收下吧, 谢谢:)

**Comment by dnknn** [comment]
@xinghaix 
https://github.com/xinghaix/download-manager/releases/tag/1.0.9
> 新增: 下载通知保留时间设置

它是无效的设置, 等同于没有,  详细具体有劳请见📧✉📨📩

**Comment by xinghaix** [comment]
> @xinghaix
> https://github.com/xinghaix/download-manager/releases/tag/1.0.9
> 
> > 新增: 下载通知保留时间设置
> 
> 它是无效的设置, 等同于没有, 详细具体有劳请见📧✉📨📩

输入数字后，需要按enter键，或者鼠标点击在设置页面其他地方才能生效。另外通知也要开启，我这边测试没有问题的

**Comment by xinghaix** [comment]
@dnknn 还有就是通知会在6秒左右的时候移入操作中心（Windows10）

**Comment by dnknn** [comment]
> 需要按enter键，或者鼠标点击在设置页面其他地方才能生效

那是基本常识的操作, 肯定要脱离input焦点才会生效.
你具体看邮箱里, 有提到.

**Comment by dnknn** [comment]
> 通知会在6秒左右的时候移入操作中心

也并没有,  💻❖Win10¹⁹⁰³  操作中心只指<kbd>Win+A</kbd> ❓

**Comment by xinghaix** [comment]
> > 需要按enter键，或者鼠标点击在设置页面其他地方才能生效
> 
> 那是基本常识的操作, 肯定要脱离input焦点才会生效.
> 你具体看邮箱里, 有提到.

没有收到你的邮件，如果你可以发送链接或者gif图片就更好

**Comment by dnknn** [comment]
> 没有收到你的邮件

昨天都能收到, 怎么就收不到了┭┮﹏┭┮

**Comment by xinghaix** [comment]
![image](https://user-images.githubusercontent.com/26537432/86078605-11e69500-bac1-11ea-95c1-19297b4747d1.png)

**Comment by dnknn** [comment]
你修改了实验参数选项吗?
chrome://flags/#enable-native-notifications

![image](https://user-images.githubusercontent.com/10995302/86078828-8c171980-bac1-11ea-8a7c-b4c76659e0b8.png)

**Comment by dnknn** [comment]
⏺🎬 
![down](https://user-images.githubusercontent.com/10995302/86079161-71917000-bac2-11ea-8f01-a033f87b6a0d.gif)

**Comment by xinghaix** [comment]
![Video_2020-06-30_110645 00_00_00-00_00_30](https://user-images.githubusercontent.com/26537432/86080137-c209cd00-bac4-11ea-924e-405fc601eeb5.gif)

**Comment by dnknn** [comment]
@xinghaix 
我的Chrome通知是独立的, 并不会移入Win+A系统通知中心去的.
你可以测试Chrome独立通知接口试试看

**Comment by xinghaix** [comment]
> @xinghaix
> 我的Chrome通知是独立的, 并不会被移入Win+A系统通知中心去接管的.
> 你可以测试Chrome独立通知接口试试看

设置都是默认的。
另外通知独立是什么意思？

**Comment by dnknn** [comment]
> 另外通知独立是什么意思？

你的Chrome通知是被系统通知接管/取代的. 而我们好像都不是的.

**Comment by xinghaix** [comment]
@dnknn 或者你想说的是通知一直显示在右下角

![image](https://user-images.githubusercontent.com/26537432/86080507-a8b55080-bac5-11ea-9a5c-a3e388291446.png)

**Comment by dnknn** [comment]
> 或者你想说的是通知一直显示在右下角
嗯是的, 就是跟系统通知不挂钩.

**Comment by xinghaix** [comment]
> > 或者你想说的是通知一直显示在右下角
> 
> 嗯是的, 就是跟系统通知不挂钩, 是独立的, 跟系统操作中心完全不沾边.
> 
> 但是谷歌通知API文档我不懂哦,

系统版本：Win10 2004 19041

**Comment by xinghaix** [comment]
@dnknn 如果你想通知一直显示在电脑右下角的话（在保留时间内），chrome有API可以设置

**Comment by dnknn** [comment]
@xinghaix 
话说其实用过N多extension, 还没见过被系统接管的通知哦.
我录制gif给你看就明白了👇

![通知](https://user-images.githubusercontent.com/10995302/86081129-2af24480-bac7-11ea-8898-f239c673d51f.gif)

**Comment by xinghaix** [comment]
@dnknn 这不是说通知被系统接管什么的，而是他们哪些插件用到了chrome API的一个参数，可以让通知一直保持在右下角而不移入到操作中心

**Comment by dnknn** [comment]
> 他们哪些插件用到了chrome API的一个参数，可以让通知一直保持在右下角而不移入到操作中心

哦原来如此, 内部开发逻辑接口的我倒是不懂了.

**Comment by xinghaix** [comment]
@dnknn 找到设置地方了。Win设置 -> 系统 -> 通知和操作
![image](https://user-images.githubusercontent.com/26537432/86083060-d43b3980-bacb-11ea-8f04-07818a5e8315.png)
![image](https://user-images.githubusercontent.com/26537432/86083070-dc937480-bacb-11ea-9779-4d9ae66e9aa4.png)

**Comment by dnknn** [comment]
@dnknn 不用.exe安装版的哦, 从来都是用zip便捷版的哦, 一个文件夹搞定浏览器数据.
所以你截图的应该是安装版才会显示.

**Comment by xinghaix** [comment]
@dnknn 😥😂 刚刚下载了一个绿色版的chrome81，的确是存在这种情况，哎，服了。

我新增一个设置项，可以长时间右小角显示，其他系统设置我没有，也不好测试

**Comment by dnknn** [comment]
> 我新增一个设置项，可以长时间右小角显示，其他系统设置我没有，也不好测试

不是长时间显示(即不能自动关闭) 那样也是没用的, 就是要设置多少秒就是多少秒的那种.

**Comment by dnknn** [comment]
@xinghaix  话说你邮件为何收不到, 里面还提到了很多, 你看看吧

**Comment by dnknn** [comment]
👍💪1.0.10有效果了, 后面能否再支持:

- ##  🉑不显示(或可设置)非主体提示文字.
![0701094908](https://user-images.githubusercontent.com/10995302/86194071-1e7df280-bb80-11ea-8cef-9455086b2910.png)

- ## 🉑点击动作的打开方式 
> (除了action动作类栏外, 也可点击通知内容的打开)

- ## 🉑有多种通知音效可选

**Comment by dnknn** [comment]
@xinghaix  

🆕最新更新, https://github.com/xinghaix/download-manager/issues/25#issuecomment-652140007
