### ISSUE TITLE
独立窗口，以及CTRL+J功能

### ISSUE THREAD

**Issue by mxhx** [xinghaix/download-manager#27]
您好：

下载器可否独立窗口弹出？可参照搜狗浏览器自带下载器。

以及点击一个按钮跳转浏览器下载列表页面（CTRL+J）功能

**Comment by mxhx** [comment]
Edge商店还在1.06版本

**Comment by xinghaix** [comment]
@mxhx 可以发个截图吗？还没用过搜狗浏览器

**Comment by mxhx** [comment]
如附件。


同时是否可以屏蔽别的下载器，优先DM，增加调用第三方下载器如IDM 迅雷 选项。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xinghai"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 下午3:33
收件人:&nbsp;"xinghaix/download-manager"<download-manager@noreply.github.com&gt;;
抄送:&nbsp;"He"<gheyc@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xinghaix/download-manager] 独立窗口，以及CTRL+J功能 (#27)





 
@mxhx 可以发个截图吗？还没用过搜狗浏览器

**Comment by xinghaix** [comment]
@mxhx 没看到图片

**Comment by yinxtno1** [comment]
他说的应该是这种
![image](https://user-images.githubusercontent.com/19941667/86427831-d8f72c00-bd1d-11ea-8fcf-88bfbe2fcbb9.png)

**Comment by xinghaix** [comment]
> 他说的应该是这种
> ![image](https://user-images.githubusercontent.com/19941667/86427831-d8f72c00-bd1d-11ea-8fcf-88bfbe2fcbb9.png)

这种可以做，但是比较麻烦，后面有时间我研究下

**Comment by yinxtno1** [comment]
能不能在右键菜单列表中加个使用迅雷下载该链接😂

**Comment by xinghaix** [comment]
> 那可不可以在右键菜单列表中加个使用迅雷下载该链接😂

应该有专门的插件可以调用迅雷、IDM等第三方下载器

**Comment by yinxtno1** [comment]
可以了，之前这个插件在 edge 上出问题了，现在好了😂🤦
