### ISSUE TITLE
根据浏览器颜色模式改变图标颜色

### ISSUE THREAD

**Issue by L1cardo** [xinghaix/download-manager#3]
我是 Mac， edge 有深色模式，希望能通过浏览器的颜色模式改变图标颜色和界面颜色
![image](https://user-images.githubusercontent.com/33802186/77932484-2f4c6d00-72e0-11ea-8ace-893c91759b20.png)

**Comment by xinghaixuanwo** [comment]
图标颜色，当前版本可以在设置 -> 主题 页中设置，自动根据系统深色模式调整图标颜色，后期肯定会加上。
下载信息面板界面后面会新增自定义主题。

**Comment by xinghaix** [comment]
@L1cardo 插件已经更新到1.0.0！

欢迎尝试全新的暗黑主题！

**Comment by L1cardo** [comment]
> @L1cardo 插件已经更新到1.0.0！
> 
> 欢迎尝试全新的暗黑主题！

我还是希望可以根据浏览器的深浅模式自动改变颜色，而不是现在的手动

**Comment by xinghaix** [comment]
@L1cardo 嗯，自动的后续再加上
你是不是再多个主机的chrome上使用这个插件，而且使用的不都是暗黑模式？
如果不是频繁的改动系统的暗黑模式，当前选择固定的主题也可以用下

**Comment by L1cardo** [comment]
我是在一个机器上（MacBook）使用 Edge 浏览器，设置为根据系统模式切换浏览器颜色模式。所以白天晚上会变化

**Comment by xinghaix** [comment]
@L1cardo 没问题，后面我将新增自动切换的功能

**Comment by xinghaix** [comment]
@L1cardo 版本`1.0.1`已经新增主题自适应功能，欢迎尝试
