### ISSUE TITLE
请教，能够支持多线程下载吗？

### ISSUE THREAD

**Issue by JieSmart** [xinghaix/download-manager#31]
请教，能够支持多线程下载吗？有时候Chrome的原始下载速度挺慢的

**Comment by xinghaix** [comment]
针对有些资源，chrome的下载速度还是不行。chrome可以开启多线程下载

**Comment by xinghaix** [comment]
@JieSmart 如果开启后还是不行，那么就得使用第三方下载工具了，你可以是复制下载链接到其他下载工具里试下

**Comment by JieSmart** [comment]
好的呢，谢谢
