### ISSUE TITLE
[BUG] 有时候会卡主不刷新下载进度

### ISSUE THREAD

**Issue by JiaoYeTan** [xinghaix/download-manager#36]
![QQ录屏20200801215825](https://user-images.githubusercontent.com/36872913/89103180-71c6b780-d442-11ea-9665-ae9ff9db46df.gif)
希望能修复

**Comment by xinghaix** [comment]
> ![QQ录屏20200801215825](https://user-images.githubusercontent.com/36872913/89103180-71c6b780-d442-11ea-9665-ae9ff9db46df.gif)
> 希望能修复

CTRL + J进入默认的下载页面，文件是否已经下载完成了呢

**Comment by JiaoYeTan** [comment]
> > ![QQ录屏20200801215825](https://user-images.githubusercontent.com/36872913/89103180-71c6b780-d442-11ea-9665-ae9ff9db46df.gif)
> > 希望能修复
> 
> CTRL + J进入默认的下载页面，文件是否已经下载完成了呢

下还是下完了,但是进度不会实时刷新

**Comment by xinghaix** [comment]
@JiaoYeTan OK，这个最近会重构下载与显示逻辑，BUG会优先解决😘

**Comment by xinghaix** [comment]
@JiaoYeTan 新版本已上线，欢迎再试下。可以发下文件链接

**Comment by JiaoYeTan** [comment]
嗯,已经没有这种情况了
