### ISSUE TITLE
下载大文件会造成chrome异常卡顿且下载失败

### ISSUE THREAD

**Issue by kayanouriko** [xinghaix/download-manager#37]
自己测试下载10g的Xcode发现有此问题，禁用扩展则可以正常下载且不会卡顿

测试环境：macOS Big Sur Beta4 / Chrome 84.0.4147.105 / 1.1.0

**Comment by xinghaix** [comment]
@kayanouriko 嗯，最近会重构代码，从而解决这个问题

**Comment by xinghaix** [comment]
@kayanouriko 新版发出来了，你试下大文件下载呢。如果可以发文件链接发出来就更好了

**Comment by kayanouriko** [comment]
还是会卡，任务管理器里面扩展占用的cpu在20%左右浮动
不是很懂扩展开发，不过感觉像是扩展在主线程上不断获取下载信息造成的卡顿
我测试的链接是：https://download.developer.apple.com/Developer_Tools/Xcode_12_beta_4/Xcode_12_beta_4.xip
不过这个链接貌似需要cookie验证才能下载到真实的文件，不知道你直接下载可不可以，https://developer.apple.com/download/ 这个是登陆后的文件下载所在地址

**Comment by xinghaix** [comment]
> 还是会卡，任务管理器里面扩展占用的cpu在20%左右浮动
> 不是很懂扩展开发，不过感觉像是扩展在主线程上不断获取下载信息造成的卡顿
> 我测试的链接是：https://download.developer.apple.com/Developer_Tools/Xcode_12_beta_4/Xcode_12_beta_4.xip
> 不过这个链接貌似需要cookie验证才能下载到真实的文件，不知道你直接下载可不可以，https://developer.apple.com/download/ 这个是登陆后的文件下载所在地址

你发这个需要APPID，我的账号忘记了找不回来。我用800M左右的文件测试，CPU占用10%，禁用扩展9%左右

**Comment by kayanouriko** [comment]
没事，反正我这边chrome下载大文件的场景也就这一个而已，其他情况一般还是专业下载工具的多。
主要需求还是下载栏自动隐藏功能和快速查看下载列表功能，别的相应功能的扩展基本是常年失修了。
感谢。
