### ISSUE TITLE
不兼容 Edge 87.0.664.57,100%但是未结束 

### ISSUE THREAD

**Issue by TaylorWolfX** [xinghaix/download-manager#59]
下载到了100%任然无法结束任务,已经持续好多个版本了,是否可以解决下

**Comment by xinghaix** [comment]
> 下载到了100%任然无法结束任务,已经持续好多个版本了,是否可以解决下

请提供一下 下载链接

**Comment by TaylorWolfX** [comment]
任意的下载链接,比如我download你的源码,其实已经下载完了,但是还是未结束!通过原下载管理可以看到任务结束了
![image](https://user-images.githubusercontent.com/23098278/104141628-b93e7000-53f2-11eb-8d28-9b4dfd5f6d84.png)
![image](https://user-images.githubusercontent.com/23098278/104141657-d3784e00-53f2-11eb-959d-5bdf9716f7b1.png)

**Comment by TaylorWolfX** [comment]
我在其他的下载管理里找到了解决办法,修改下载设计即可
![image](https://user-images.githubusercontent.com/23098278/104145318-733cd880-5401-11eb-94f4-bf0a144ca22d.png)
