### ISSUE TITLE
Chrome商店已下架

### ISSUE THREAD

**Issue by wen-carl** [xinghaix/download-manager#75]
如题。

**Comment by kktt007** [comment]
是的,快上架,这是唯一一款我下载中断还保留下载信息的,最近有一个123云盘,快是快,但是他没有下载链接,找不到下载地址,我点击下载再取消,然后在download-manager里面居然看到下载地址了...牛逼

**Comment by WilliamWangshao** [comment]
隐私问题？

**Comment by zhj9709** [comment]
我用了很多下载管理器，就喜欢这款，可惜下架了，我也希望快点上架

**Comment by xinghaix** [comment]
@kktt007 @zhj9709 @wen-carl @WilliamWangshao @haiGodzilla  已申请重新上线了

**Comment by xinghaix** [comment]
伙伴们，已经重新上线啦
