### ISSUE TITLE
插件经常被停用

### ISSUE THREAD

**Issue by zhj9709** [xinghaix/download-manager#76]
![image](https://user-images.githubusercontent.com/13991774/146638363-9964cd1b-8c93-4c97-8062-a1564cda085e.png)

已经删除重新下载过

还在chrome商店里

**Comment by zhj9709** [comment]
重启浏览器后没有这个提示了

**Comment by zhj9709** [comment]
> 重启浏览器后没有这个提示了

不怎么管用，还是时不时被停用

**Comment by xinghaix** [comment]
> > 重启浏览器后没有这个提示了
> 
> 不怎么管用，还是时不时被停用

![image](https://user-images.githubusercontent.com/26537432/146701211-59ee10d3-5d3e-4e01-905d-f7020ff51c14.png)
点下更新，更新下插件就可以了

**Comment by zhj9709** [comment]
> > > 重启浏览器后没有这个提示了
> > 
> > 
> > 不怎么管用，还是时不时被停用
> 
> ![image](https://user-images.githubusercontent.com/26537432/146701211-59ee10d3-5d3e-4e01-905d-f7020ff51c14.png) 点下更新，更新下插件就可以了

没有这个更新，我的应该是最新版了，我删除重装过

**Comment by zhj9709** [comment]
又没问题了，这插件还是很好用的
