### ISSUE TITLE
更新后Chrome 提示：This extension violates the Chrome Web Store policy.

### ISSUE THREAD

**Issue by Alex-NKG** [xinghaix/download-manager#77]
更新最新版/从新安装后依旧提升This extension violates the Chrome Web Store policy. 并且每次重启Chrome后均被禁用

**Comment by xinghaix** [comment]
![image](https://user-images.githubusercontent.com/26537432/146701248-ca821b8f-2bee-42be-966f-82d9c6903106.png)
更新下插件试试
