### ISSUE TITLE
剩余时间显示有问题

### ISSUE THREAD

**Issue by a254476321** [xinghaix/download-manager#8]
2小时会显示成剩余2分钟，再提个小建议，希望加个清除已删除的文件

**Comment by xinghaix** [comment]
@a254476321 的确存在小时显示成分钟的问题，下一版解决。
新增清除已删除文件的功能，之前有其他人也提到过，我考虑下

**Comment by xinghaix** [comment]
@a254476321 剩余时间显示问题已解决

**Comment by xinghaix** [comment]
至于添加清空以删除文件的功能，我已将加入计划中
