### ISSUE TITLE
French Translation...

### ISSUE THREAD

**Issue by EverdeenCS** [xinghaix/download-manager#9]
Hi to the creator,

The **french** translation is an automatic translation isn't it ?
If you want I can help you with **french translation**...

Send me a message :D

**Comment by xinghaix** [comment]
@EverdeenCS Yes, it was translated by Google. I will be appreciate if you can help it!

The following link is the french translation content.
https://github.com/xinghaix/download-manager/blob/master/public/_locales/fr/messages.json.

all the text display content of the plug-in is the `message `field.

**Comment by xinghaix** [comment]
@EverdeenCS You can download this json file, upload here after modification

**Comment by EverdeenCS** [comment]
OK
I'm just downloading file...
As soon as I've translated the file, I will upload it...

**Comment by EverdeenCS** [comment]
I will download english version to be sure my translation is accurate...

**Comment by EverdeenCS** [comment]
Hello...

The file is ready... But I can't upload it in public folder...
Because, I quote : "Uploads are disabled. File uploads require push access to this repository."...
[messages.json.zip](https://github.com/xinghaix/download-manager/files/4522352/messages.json.zip)

**Comment by xinghaix** [comment]
Thanks very much!
I will check it over,and then it will be in the next version!

**Comment by EverdeenCS** [comment]
No problem.

I've ever changed json file in my extension folder :D

**Comment by xinghaix** [comment]
@EverdeenCS The plugin has been updated to 1.0.0！
